EMAIL:
    Smtp_Server: smtp.tanxiumei, com
    Smtp_Sender: test @ tenez.com
    Password: Password
    OnLine_Receiver: techtest @ tenez.com
    Pro_Receiver: tester @ tenez.com
    Test_Receiver: tester @ tenez.com
    Text_description: API用例执行情况
    resultPath: html / body / div[1] / p[4]
    on - off: on

DB:
    host: localhost
    username: myself
    password: skyyj
    port: 3306
    database: mystudycookie1
cookie1:
  domain: .yiyao.cc
  expiry: 1521558688.480118
  httpOnly: false
  name: _ui_
  path: /
  secure: false
  value: HSX9fJjjCIImOJoPUkv/QA==
